apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    run: tower-setup-job
  name: tower-setup-job
  namespace: ansible-runner
spec:
  template:
    spec:
      activeDeadlineSeconds: 600
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/ansible-runner/ansible-runner:latest
          env:
            - name: GIT_DIRECTORY
              value: "/tmp/git/acm-demo"
            - name: GIT_URL
              value: "https://github.com/sa-ne/acm-demo.git"
            - name: ANSIBLE_PLAYBOOK
              value: "ansible/playbooks/tower-setup.yaml"
            - name: ANSIBLE_CONFIG
              value: /var/secrets/tower-setup/ansible.cfg
          command:
            - /bin/bash
            - -c
            - |
              mkdir -p $GIT_DIRECTORY
              git clone $GIT_URL $GIT_DIRECTORY
              ansible-galaxy collection install -r $GIT_DIRECTORY/ansible/collections/requirements.yaml
              ansible-playbook $GIT_DIRECTORY/$ANSIBLE_PLAYBOOK
          volumeMounts:
            - name: tower-setup
              mountPath: /var/secrets/tower-setup
              readOnly: true
          volumeMounts:
            - name: route53-zone-credentials
              mountPath: /var/secrets/route53-zone-credentials
              readOnly: true
          imagePullPolicy: Always
          name: tower-install-job
      volumes:
        - name: tower-setup
          secret:
            secretName: tower-setup
            defaultMode: 0444
        - name: route53-zone-credentials
          secret:
            secretName: route53-zone-credentials
            defaultMode: 0444
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: ansible-runner-sa
      serviceAccountName: ansible-runner-sa
      terminationGracePeriodSeconds: 30