apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acm-demo-gitops
  namespace: acm-demo-gitops
  annotations:
      apps.open-cluster-management.io/git-branch: main
      apps.open-cluster-management.io/github-path: gitops/manifests/clusters/acm-hub/advanced-cluster-management-gitops/base
      apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: acm-demo-gitops/acm-demo-gitops
  placement:
    local: true