apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: all-environments
  namespace: acm-demo-gitops
  labels:
    app: dev-cluster
  annotations:
      apps.open-cluster-management.io/git-branch: main
      apps.open-cluster-management.io/github-path: gitops/manifests/clusters/all/policies/cluster/base
      apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: acm-demo-gitops/acm-demo-gitops
  placement:
    local: true