apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: omc-app-channel
  namespace: acm-demo-gitops
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  type: GitHub
  pathname: https://github.com/sa-ne/openshift-mini-console.git