apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: omc-app-root
  namespace: acm-demo-gitops
  annotations:
      apps.open-cluster-management.io/git-branch: main
      apps.open-cluster-management.io/github-path: deploy/acm
      apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: acm-demo-gitops/omc-app-channel
  placement:
    local: true