acm_version: "2.2"
acm:
  acm_hub_kubeconfig: /home/chris/ipi/aws/acm-hub/auth/kubeconfig
  spokes:
    - name: dev
      kubeconfig: /home/chris/ipi/aws/acm-demo-dev/auth/kubeconfig
      labels:
        cloud: auto-detect
        vendor: auto-detect
        name: dev
        environment: dev
    - name: prod-1
      kubeconfig: /home/chris/ipi/aws/acm-demo-prod-1/auth/kubeconfig
      labels:
        cloud: auto-detect
        vendor: auto-detect
        name: prod-1
        environment: prod
    - name: prod-2
      kubeconfig: /home/chris/ipi/aws/acm-demo-prod-2/auth/kubeconfig
      labels:
        cloud: auto-detect
        vendor: auto-detect
        name: prod-2
        environment: prod